### PR TITLE
Laravel 10 Support

### PR DESCRIPTION
**Pull request by schonhoff**
This PR adds the Support for Laravel 10.
It includes a switch to PHPUnit 10 and therefore a rewritten phpunit.xml.dist and an update to .gitignore

All tests were green for Lumen and for Laravel 10.

### CODE REVIEW

**Comment by axlon** [comment]
It appears something is trying to install a Composer plugin during test runs on older versions, causing them to fail

**Comment by schonhoff** [comment]
Carbon uses the plugin to show the users a migration to carbon version 2.

here is a snippet from my local composer.lock after I installed Laravel 5.5.*

```json

        {
            "name": "nesbot/carbon",
            "version": "1.39.1",
            "source": {
                "type": "git",
                "url": "https://github.com/briannesbitt/Carbon.git",
                "reference": "4be0c005164249208ce1b5ca633cd57bdd42ff33"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/briannesbitt/Carbon/zipball/4be0c005164249208ce1b5ca633cd57bdd42ff33",
                "reference": "4be0c005164249208ce1b5ca633cd57bdd42ff33",
                "shasum": ""
            },
            "require": {
                "kylekatarnls/update-helper": "^1.1",
                "php": ">=5.3.9",
                "symfony/translation": "~2.6 || ~3.0 || ~4.0"
            },
            "require-dev": {
                "composer/composer": "^1.2",
                "friendsofphp/php-cs-fixer": "~2",
                "phpunit/phpunit": "^4.8.35 || ^5.7"
            },
            "bin": [
                "bin/upgrade-carbon"
            ],
            "type": "library",
            "extra": {
                "update-helper": "Carbon\\Upgrade",
                "laravel": {
                    "providers": [
                        "Carbon\\Laravel\\ServiceProvider"
                    ]
                }
            },
            "autoload": {
                "psr-4": {
                    "": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Brian Nesbitt",
                    "email": "brian@nesbot.com",
                    "homepage": "http://nesbot.com"
                }
            ],
            "description": "A simple API extension for DateTime.",
            "homepage": "http://carbon.nesbot.com",
            "keywords": [
                "date",
                "datetime",
                "time"
            ],
            "support": {
                "issues": "https://github.com/briannesbitt/Carbon/issues",
                "source": "https://github.com/briannesbitt/Carbon"
            },
            "time": "2019-10-14T05:51:36+00:00"
        },
```

To allow the plugin we need to change either the composer.json to include it

```json
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "kylekatarnls/update-helper": true
        }
    },
```

or we need to update the workflow to allow the plugin. But I'm not sure with how to handle it.

**Comment by schonhoff** [comment]
That looked pretty good :-) Thanks for your help!

**Comment by axlon** [comment]
Thank you!

**Pull request merged**
