### PR TITLE
Add a more robust validation for german postalcodes

### PR DESCRIPTION
**Pull request by heikokrebs**
A little bit better validation of German postal codes that takes some special aspects into account.

### CODE REVIEW

**Comment by axlon** [comment]
Hello @heikokrebs,

Thank you for your contribution, however I am currently not accepting any direct changes to the formats file as it is auto-generated from Google's API and your changes would be overwritten the next time it is generated.

I am working on adding support for manual overrides in the upcoming 3.0 version, but I do not have an estimated release date for this yet.

**Comment by heikokrebs** [comment]
Hey @axlon,

what Google API is that?

**Comment by axlon** [comment]
Their address metadata service, which can be found [here](https://github.com/google/libaddressinput/wiki/AddressValidationMetadata). The format for Germany specifically can be found [here](https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/DE).

**Comment by heikokrebs** [comment]
@axlon thanks a lot! Looking forward to v3.0!

Thanks for your great work!

**Pull request closed without merging**
